title = "My Portfolio"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 10
enableEmoji = true

[markup.highlight]
noClasses = false

[params]
author = "Sambhav Dave"
description = "Sambhav's portfolio"
keywords = "sdet,developer,portfolio,test automation,qa automation,qa,testing"
info = [
        "Software Engineer | SDET",
        "Skilled sofware engineer with 4+ years of full-time professional experience",
    ]
avatarURL = "images/dp.jpg"

# Git Commit in Footer, uncomment the line below to enable it
#commit = "https://github.com/luizdepra/hugo-coder/tree/"

# Right To Left, shift content direction for languagues such as Arabic
rtl = false

# Specify light/dark colorscheme (auto/dark/light)
colorScheme = "dark"

# Custom CSS
customCSS = []

# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/mr-possible"
target = "_blank"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 2
url = "https://twitter.com/DaveSambhav"
target = "_blank"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 3
url = "https://www.linkedin.com/in/sambhav6197/"
target = "_blank"

[[params.social]]
name = "Medium"
icon = "fa fa-2x fa-medium"
weight = 4
url = "https://medium.com/@mr_possible"
target = "_blank"

[[params.social]]
name = "Youtube"
icon = "fa fa-2x fa-youtube"
weight = 5
url = "https://youtube.com/@mr_possible6197?si=gdgCWTw9bOTrOdjt"
target = "_blank"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "Home"
weight = 1
url = "/"

[[languages.en.menu.main]]
name = "About"
weight = 2
url = "/about"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "/projects"

[[languages.en.menu.main]]
name = "Open Source Contributions"
weight = 3
url = "/open-source"