export const siteConfig = {
  /** Suffix for subpage titles: "About Sambhav Dave | Sambhav Dave". */
  title: 'Sambhav Dave',
  /**
   * Used verbatim as the homepage <title>. Carries the role keywords that the
   * bare name doesn't, for people searching a name they were handed.
   */
  titleDefault: 'Sambhav Dave — Software Engineer & SDET',
  description: 'Software Engineer | SDET',
  /** Schema.org Person.jobTitle — no pipes, unlike `description`. */
  jobTitle: 'Software Development Engineer in Test',
  tagline:
    "Seven years making other people's software prove it works — test strategy, automation, and the occasional blog post",
  author: 'Sambhav Dave',
  /** Must match `site` in astro.config.mjs; used to absolutize URLs in JSON-LD. */
  url: 'https://www.sambhav.blog',
  /** 224x224 WebP generated from assets/dp-source.jpg by `npm run avatar`. */
  avatar: '/images/dp.webp',
  /** Default social-share card, generated by `npm run og`. */
  ogImage: '/og-default.png',
  ogImageAlt: 'Sambhav Dave — Software Engineer | SDET',
  terminal: {
    user: 'sambhav',
    host: 'portfolio',
    cwd: '~',
  },
  social: [
    {
      name: 'GitHub',
      url: 'https://github.com/mr-possible',
      icon: 'github',
    },
    {
      name: 'Twitter',
      url: 'https://twitter.com/DaveSambhav',
      icon: 'twitter',
    },
    {
      name: 'LinkedIn',
      url: 'https://www.linkedin.com/in/sambhav6197/',
      icon: 'linkedin',
    },
    {
      name: 'Medium',
      url: 'https://medium.com/@mr_possible',
      icon: 'medium',
    },
    {
      name: 'YouTube',
      // Canonical channel URL — the ?si= share token that was here is a
      // per-click tracking artifact and shouldn't appear in `sameAs`.
      url: 'https://www.youtube.com/@mr_possible6197',
      icon: 'youtube',
    },
  ],
  nav: [
    { name: 'Home', path: '/' },
    { name: 'About', path: '/about' },
    { name: 'Projects', path: '/projects' },
    { name: 'Blog', path: '/blog' },
  ],
} as const;
